#!/usr/bin/env bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (use sudo)" >&2
   exit 1
fi

git clone https://github.com/Rrominet/fxos_gui-lib
cd fxos_gui-lib
chmod +x ./build-n-install
./build-n-install
cd ..

mkdir -p ./prjs
mv ./fxos_gui-lib ./prjs/mlgui.2

cd ./fxpipe/core
mkdir -p ./build
cd ./build
chmod +x ../make
chmod +x ../install
../make release keep-same libs="../../cpp-utils_dependencies" fm="../../cpp-utils" prjs="../../prjs"
../install

cd ../../gui
mkdir -p ./build
cd ./build
chmod +x ../make
chmod +x ../install
../make release keep-same libs="../../cpp-utils_dependencies" fm="../../cpp-utils" prjs="../../prjs"
../install
