#!/usr/bin/env bash

mkdir /opt/fxpipe
cp -v ./fxpipe /opt/fxpipe/fxpipe
chmod +x /opt/fxpipe/fxpipe

cp -v ../../core/build/fxpipe-core /opt/fxpipe/fxpipe-core
chmod +x /opt/fxpipe/fxpipe-core

cp -v ./version /opt/fxpipe/version
cp -v ./fxpipe.css /opt/fxpipe/fxpipe.css

cp -rv ./html /opt/fxpipe/html

rm -fv /usr/local/bin/fxpipe
ln -s /opt/fxpipe/fxpipe /usr/local/bin/fxpipe

chmod -R 777 /opt/fxpipe

echo "fxpipe installed."
