#!/usr/bin/env python3

from ml import build
from ml.boilerplate import cpp
from ml import fileTools as ft
import os
import sys
import subprocess
import shutil
sys.path.append("../")

def mdToHtmls() : 
    if os.path.isdir("./html") :
        shutil.rmtree("./html")

    mds = os.listdir("../src/md")
    os.makedirs("./html", exist_ok=True)
    shutil.copyfile(fxhtml + "/fxhtml.css", "./html/style.css")
    for md in mds : 
        cmd = ["/media/romain/Donnees/ProgramLinux/bin/mdtohtml", "../src/md/" + md]
        subprocess.run(cmd)
        os.rename("../src/md/" + ft.baseName(md) + ".html", "./html/" + ft.baseName(md) + ".html")

fm = "../../../../frameworks"
libs = "../../../../libs"
prjs = "../../.."

b = build.create("fxpipe", sys.argv)

fxhtml = "../../../fxhtml/build"

for arg in sys.argv:
    if "libs=" in arg:
        libs = arg.split("=")[1]
    elif "fm=" in arg or "cpp-utils=" in arg:
        fm = arg.split("=")[1]
    elif "prjs=" in arg:
        prjs = arg.split("=")[1]

for arg in sys.argv:
    if "libs=" in arg:
        libs = arg.split("=")[1]
    elif "fm=" in arg or "cpp-utils=" in arg:
        fm = arg.split("=")[1]
    elif "prjs=" in arg:
        prjs = arg.split("=")[1]

cpp.generate("../src")

includes = [
    fxhtml + "/api",
    "../src",
    libs + "/json",
    libs + "/eigen",
    #no need to include boost here, just install it systemwide with apt install libboost-all-dev
    fm,
    prjs,
        ]

srcs = [
        "../src",
        ]

libs = [
        ]

defs = ["NO_LOG"]

b.static = False
b.includes = includes
b.addToSrcs(srcs)
b.addToLibs(libs)
b.definitions += defs
b.addInstalledLibrary("gtkmm-4.0")

# sudo apt install libwebkitgtk-6.0-dev
b.addInstalledLibrary("webkitgtk-6.0")

b.addToLibs("stdc++fs")
b.addToLibs("boost_filesystem")

if "release" in sys.argv:
    b.addToLibs(fm + "/build/libmlapi.a")
    b.addToLibs(prjs + "/mlgui.2/build/libmlgui.a")
else : 
    b.addToLibs(fm + "/build/libmlapi_debug.a")
    b.addToLibs(prjs + "/mlgui.2/build/libmlgui_debug.a")

if("clean" in sys.argv or "clear" in sys.argv):
    b.clean()
    exit()
else:
    #mdToHtmls()
    b.build()
