#!/usr/bin/env python3

from ml import build
from ml.boilerplate import cpp
import sys
import os
import shutil
sys.path.append("../")

cpp.generate("../src")

fm = "../../../../frameworks"
libs = "../../../../libs"

for arg in sys.argv:
    if "libs=" in arg:
        libs = arg.split("=")[1]
    elif "fm=" in arg or "cpp-utils=" in arg:
        fm = arg.split("=")[1]
    elif "prjs=" in arg:
        prjs = arg.split("=")[1]

includes = [
    "../src",
    fm,
    libs + "/json",
    libs + "/eigen",
        ]

srcs = [
        "../src",
        ]

b = build.create("fxpipe-core", sys.argv)
b.includes = includes
b.addToSrcs(srcs)

b.addToLibs("stdc++fs")
b.addToLibs("boost_filesystem")

if "release" in sys.argv:
    b.addToLibs(fm + "/build/libmlapi.a")
else :
    b.addToLibs(fm + "/build/libmlapi_debug.a")

if ("clean" in sys.argv or "clear" in sys.argv) :
    b.clean()
else :
    b.build()
